apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      containers:
        - name: product-catalogue
          image: boxofpencil/product-catalogue:v1
          ports:
            - containerPort: 80
          env:
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: product-catalogue-config
                  key: APP_TITLE
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: product-catalogue-config
                  key: ENVIRONMENT